"""empty message

Revision ID: faa3b9b24bab
Revises: 749ecabc2be7
Create Date: 2024-05-30 15:45:02.335956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'faa3b9b24bab'
down_revision = '749ecabc2be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=False))
        batch_op.drop_column('descripton')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripton', mysql.VARCHAR(length=500), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
